### ISSUE TITLE
Texto para o "Sobre"

### ISSUE THREAD

**Issue by rochacbruno** [CastalioPodcast/CastalioPodcast.github.io#100]
# Castálio

O Castálio é um podcast semanal publicado todas as segundas às 11 horas. Og, Elyézer e Bruno falam sobre tecnologia, desenvolvimento de software, linguagens de programação e o mundo do Open Source!

Além de entrevistas com pessoas da comunidade de tecnologia e open source, também temos os episódios temáticos e os 'Tech News', trazendo as principais notícias e dicas de bibliotecas e novas tecnologias. Além disso, o Og Maciel traz um pouco de seu interesse em literatura com os Book Reviews.

De vez em quando às quartas, gravamos os episódios ao vivo pelo YouTube e você está convidado a participar! Basta acompanhar nosso Twitter ou Facebook para ficar sabendo quando estaremos ao vivo!

# Como surgiu o Castálio?

O Castálio Podcast é fruto da imaginação e curiosidade incansável de Og Maciel, um brasileiro que desde 1991 mora nos Estados Unidos mas que nunca deixou de prestigiar suas raizes!

Em 2014 Elyézer se juntou à equipe e no final de 2016 Bruno Rocha também 
foi convidado a participar como membro do time Castálio!

Em 2017 o podcast completou 6 anos(!!!) e nós gravamos um episódio de comemoração 
contando algumas curiosidades que você pode ouvir em [link para o episodio de 6 anos]

# O que significa "Castálio" ?

Castália é o nome de uma **náiade** (uma ninfa aquática) que foi
transformada por Apolo em nascente de água, perto de **Delfos** (a
**Fonte de Castália**) e na base do **Monte Parnaso**.

Castália inspirava o génio poético daqueles que bebessem das suas águas
ou ouvissem o movimento das suas águas. A água sagrada também era usada
para as limpezas dos templos em Delfos.[Fonte: `wikipedia`_]

Para saber mais sobre como o nome foi escolhido escute o primeiro episódio aqui: [link para o episodio 1]

# Participe

Caso você tenha alguma sugestão para o nosso próximo convidado, nos envie sua idéia para o nosso e-mail e inscreva-se em nosso canal para participar das gravações ao vivo!

------------------------------

@elyezer @omaciel vamos definir aqui nesta issue o texto do "sobre", comentem com as edições e sugestões. (depois colocamos os links)

**Comment by omaciel** [comment]
Buenas!

Primeiro, 👍  por estar atualizando a pagina :)

Segundo, eu não gostaria de perder esta parte aqui:

> O Castálio Podcast é fruto da imaginação e curiosidade incansável de Og Maciel, um brasileiro que desde 1991 mora nos Estados Unidos mas que nunca deixou de prestigiar suas raizes!

Eu acho que o texto acima mostra a historia do podcast, como que ele 'came about' e que eu fundei ele :)

Terceiro, seria ainda assim interessante manter ou criar uma seção sobre os participantes, uma mini biografia, e links para contato?

Por último, algumas sugestões para o texto deste issue, que esta' muito legal by the way!

```diff
-Além de entrevistas com pessoas da comunidade de tecnologia e open source, também temos os episódios temáticos e os Tech News trazendo as principais notícias e dicas de bibliotecas e novas tecnologias e além disso o Og Maciel traz um pouco do seu vasto conhecimento em literatura com os Book Reviews.
+Além de entrevistas com pessoas da comunidade de tecnologia e open source, também temos os episódios temáticos e os 'Tech News', trazendo as principais notícias e dicas de bibliotecas e novas tecnologias. Além disso, o Og Maciel traz um pouco de seu interesse em literatura com os Book Reviews.
```

e

```diff
-De vez em quando às quartas gravamos os episódios ao vivo pelo YouTube e você está convidado a participar, basta acompanhar nosso twitter ou facebook para ficar sabendo quando estaremos ao vivo!
+De vez em quando às quartas, gravamos os episódios ao vivo pelo YouTube e você está convidado a participar! Basta acompanhar nosso Twitter ou Facebook para ficar sabendo quando estaremos ao vivo!
```

**Comment by rochacbruno** [comment]
> Terceiro, seria ainda assim interessante manter ou criar uma seção sobre os participantes, uma mini biografia, e links para contato?

@omaciel Sim! a parte com as fotos e biografias de cada um a gente mantém como está! esse é só o texto para ir acima!

**Comment by rochacbruno** [comment]
@omaciel texto atualizado! veja se precisa mudar algo mais

**Comment by omaciel** [comment]
@rochacbruno show de bola! Alguns comentários:

```diff
-Em ____ Elyézer se juntou ao Castálio para colaborar com Og Maciel
 e no final de 2016 Bruno Rocha também foi convidado a participar como 
membro do time Castálio!
+Em ____ Elyézer se juntou à equipe e no final de 2016 Bruno Rocha também 
foi convidado a participar como membro do time Castálio!
```

```diff
-O podcast já tem 6 anos! e nós gravamos um episódio de comemoração 
contando algumas curiosidades e você pode ouvir em [link para o episodio de 6 anos]
+Em 2017 o podcast completou 6 anos(!!!) e nós gravamos um episódio de comemoração 
contando algumas curiosidades que você pode ouvir em [link para o episodio de 6 anos]
```

**Comment by rochacbruno** [comment]
@elyezer ACK?

**Comment by elyezer** [comment]
ACK, eu editei a issue e coloquei 2014 como sendo o ano que comecei a participar. Esse http://castalio.info/episodio-55-editor-vim.html foi o primeiro episodio que comecei e ele foi lancado em 23 de Novembro de 2014.

**Comment by omaciel** [comment]
@elyezer @rochacbruno ping?
